crawler:
  ling-gang-gov-cn:
    basePath: https://www.lingang.gov.cn
    index: https://www.lingang.gov.cn/html/website/lg/index/government/file/index.html
  proxy:
    host: 127.0.0.1
    port: 9001
