backend:
  tenantId: BW61
  location: https://example.com/name/api

photo:
  url: ./static/img

gateway:
  accessKey: key
  secretKey: sec
  url: url

news:
  type:
    newsId: BW6711
    policyId: BW6710
    specialId: BW6763
  status:
    publishedId: BW5585
    unpublishedId: BW5586
  isExternalId: BW6832

#第一次生产之后isInit后续应改为false
crawler:
  isInit: true
  ling-gang-gov-cn:
    basePath: https://www.lingang.gov.cn
    index: https://www.lingang.gov.cn/html/website/lg/index/government/file/index.html
    media: https://www.lingang.gov.cn/html/website/lg//index/news/Mediafocus/
  proxy:
    host: 127.0.0.1
    port: 9001
    isProxyUsing: false
  driver:
    chrome:
      linux: ./chromedriver/linux/chromedriver
      windows: chromedriver/windows/chromedriver.exe
    firefox:
      linux: ./firefoxdriver/linux/geckodriver
      windows: ./firefoxdriver/windows/geckodriver.exe